ETH Up Token BID:$0.52 ASK:$0.53 Down Token BID:$0.47 ASK:$0.48 remaining time:9m 26s market_timestamp:1775078100
BTC Up Token BID:$0.74 ASK:$0.75 Down Token BID:$0.25 ASK:$0.26 remaining time:9m 26s market_timestamp:1775078100

ETH Up Token BID:$0.53 ASK:$0.55 Down Token BID:$0.45 ASK:$0.47 remaining time:9m 25s market_timestamp:1775078100
BTC Up Token BID:$0.74 ASK:$0.75 Down Token BID:$0.25 ASK:$0.26 remaining time:9m 25s market_timestamp:1775078100

ETH Up Token BID:$0.55 ASK:$0.56 Down Token BID:$0.44 ASK:$0.45 remaining time:9m 24s market_timestamp:1775078100
BTC Up Token BID:$0.74 ASK:$0.75 Down Token BID:$0.25 ASK:$0.26 remaining time:9m 24s market_timestamp:1775078100

ETH Up Token BID:$0.55 ASK:$0.56 Down Token BID:$0.44 ASK:$0.45 remaining time:9m 23s market_timestamp:1775078100
BTC Up Token BID:$0.74 ASK:$0.75 Down Token BID:$0.25 ASK:$0.26 remaining time:9m 23s market_timestamp:1775078100

ETH Up Token BID:$0.55 ASK:$0.56 Down Token BID:$0.44 ASK:$0.45 remaining time:9m 22s market_timestamp:1775078100
BTC Up Token BID:$0.74 ASK:$0.75 Down Token BID:$0.25 ASK:$0.26 remaining time:9m 22s market_timestamp:1775078100

ETH Up Token BID:$0.55 ASK:$0.56 Down Token BID:$0.44 ASK:$0.45 remaining time:9m 21s market_timestamp:1775078100
BTC Up Token BID:$0.74 ASK:$0.75 Down Token BID:$0.25 ASK:$0.26 remaining time:9m 21s market_timestamp:1775078100

ETH Up Token BID:$0.55 ASK:$0.57 Down Token BID:$0.43 ASK:$0.45 remaining time:9m 20s market_timestamp:1775078100
BTC Up Token BID:$0.74 ASK:$0.75 Down Token BID:$0.25 ASK:$0.26 remaining time:9m 20s market_timestamp:1775078100

ETH Up Token BID:$0.55 ASK:$0.56 Down Token BID:$0.44 ASK:$0.45 remaining time:9m 19s market_timestamp:1775078100
BTC Up Token BID:$0.74 ASK:$0.75 Down Token BID:$0.25 ASK:$0.26 remaining time:9m 19s market_timestamp:1775078100

ETH Up Token BID:$0.57 ASK:$0.58 Down Token BID:$0.42 ASK:$0.43 remaining time:9m 18s market_timestamp:1775078100
BTC Up Token BID:$0.76 ASK:$0.77 Down Token BID:$0.23 ASK:$0.24 remaining time:9m 18s market_timestamp:1775078100

ETH Up Token BID:$0.58 ASK:$0.59 Down Token BID:$0.41 ASK:$0.42 remaining time:9m 17s market_timestamp:1775078100
BTC Up Token BID:$0.76 ASK:$0.77 Down Token BID:$0.23 ASK:$0.24 remaining time:9m 17s market_timestamp:1775078100

ETH Up Token BID:$0.57 ASK:$0.58 Down Token BID:$0.42 ASK:$0.43 remaining time:9m 16s market_timestamp:1775078100
BTC Up Token BID:$0.76 ASK:$0.77 Down Token BID:$0.23 ASK:$0.24 remaining time:9m 16s market_timestamp:1775078100

ETH Up Token BID:$0.18 ASK:$0.19 Down Token BID:$0.81 ASK:$0.82 remaining time:11m 46s market_timestamp:1775080800
BTC Up Token BID:$0.18 ASK:$0.19 Down Token BID:$0.81 ASK:$0.82 remaining time:11m 46s market_timestamp:1775080800

ETH Up Token BID:$0.18 ASK:$0.19 Down Token BID:$0.81 ASK:$0.82 remaining time:11m 45s market_timestamp:1775080800
BTC Up Token BID:$0.18 ASK:$0.19 Down Token BID:$0.81 ASK:$0.82 remaining time:11m 45s market_timestamp:1775080800

ETH Up Token BID:$0.18 ASK:$0.19 Down Token BID:$0.81 ASK:$0.82 remaining time:11m 44s market_timestamp:1775080800
BTC Up Token BID:$0.17 ASK:$0.18 Down Token BID:$0.82 ASK:$0.83 remaining time:11m 44s market_timestamp:1775080800

ETH Up Token BID:$0.13 ASK:$0.14 Down Token BID:$0.86 ASK:$0.87 remaining time:11m 43s market_timestamp:1775080800
BTC Up Token BID:$0.15 ASK:$0.16 Down Token BID:$0.84 ASK:$0.85 remaining time:11m 43s market_timestamp:1775080800

ETH Up Token BID:$0.12 ASK:$0.13 Down Token BID:$0.87 ASK:$0.88 remaining time:11m 42s market_timestamp:1775080800
BTC Up Token BID:$0.15 ASK:$0.16 Down Token BID:$0.84 ASK:$0.85 remaining time:11m 42s market_timestamp:1775080800

ETH Up Token BID:$0.13 ASK:$0.14 Down Token BID:$0.86 ASK:$0.87 remaining time:11m 41s market_timestamp:1775080800
BTC Up Token BID:$0.15 ASK:$0.16 Down Token BID:$0.84 ASK:$0.85 remaining time:11m 41s market_timestamp:1775080800

ETH Up Token BID:$0.13 ASK:$0.15 Down Token BID:$0.85 ASK:$0.87 remaining time:11m 40s market_timestamp:1775080800
BTC Up Token BID:$0.15 ASK:$0.16 Down Token BID:$0.84 ASK:$0.85 remaining time:11m 40s market_timestamp:1775080800

ETH Up Token BID:$0.13 ASK:$0.14 Down Token BID:$0.86 ASK:$0.87 remaining time:11m 39s market_timestamp:1775080800
BTC Up Token BID:$0.15 ASK:$0.16 Down Token BID:$0.84 ASK:$0.85 remaining time:11m 39s market_timestamp:1775080800

ETH Up Token BID:$0.13 ASK:$0.14 Down Token BID:$0.86 ASK:$0.87 remaining time:11m 37s market_timestamp:1775080800
BTC Up Token BID:$0.15 ASK:$0.16 Down Token BID:$0.84 ASK:$0.85 remaining time:11m 37s market_timestamp:1775080800

ETH Up Token BID:$0.12 ASK:$0.13 Down Token BID:$0.87 ASK:$0.88 remaining time:11m 36s market_timestamp:1775080800
BTC Up Token BID:$0.14 ASK:$0.15 Down Token BID:$0.85 ASK:$0.86 remaining time:11m 36s market_timestamp:1775080800

ETH Up Token BID:$0.15 ASK:$0.16 Down Token BID:$0.84 ASK:$0.85 remaining time:11m 35s market_timestamp:1775080800
BTC Up Token BID:$0.16 ASK:$0.17 Down Token BID:$0.83 ASK:$0.84 remaining time:11m 35s market_timestamp:1775080800

ETH Up Token BID:$0.17 ASK:$0.18 Down Token BID:$0.82 ASK:$0.83 remaining time:11m 34s market_timestamp:1775080800
BTC Up Token BID:$0.18 ASK:$0.20 Down Token BID:$0.80 ASK:$0.82 remaining time:11m 34s market_timestamp:1775080800

ETH Up Token BID:$0.16 ASK:$0.17 Down Token BID:$0.83 ASK:$0.84 remaining time:11m 33s market_timestamp:1775080800
BTC Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:11m 33s market_timestamp:1775080800

ETH Up Token BID:$0.16 ASK:$0.17 Down Token BID:$0.83 ASK:$0.84 remaining time:11m 32s market_timestamp:1775080800
BTC Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:11m 32s market_timestamp:1775080800

ETH Up Token BID:$0.16 ASK:$0.17 Down Token BID:$0.83 ASK:$0.84 remaining time:11m 31s market_timestamp:1775080800
BTC Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:11m 31s market_timestamp:1775080800

ETH Up Token BID:$0.16 ASK:$0.17 Down Token BID:$0.83 ASK:$0.84 remaining time:11m 30s market_timestamp:1775080800
BTC Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:11m 30s market_timestamp:1775080800

ETH Up Token BID:$0.18 ASK:$0.19 Down Token BID:$0.81 ASK:$0.82 remaining time:11m 29s market_timestamp:1775080800
BTC Up Token BID:$0.21 ASK:$0.22 Down Token BID:$0.78 ASK:$0.79 remaining time:11m 29s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:11m 28s market_timestamp:1775080800
BTC Up Token BID:$0.23 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 28s market_timestamp:1775080800

ETH Up Token BID:$0.18 ASK:$0.19 Down Token BID:$0.81 ASK:$0.82 remaining time:11m 27s market_timestamp:1775080800
BTC Up Token BID:$0.23 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 27s market_timestamp:1775080800

ETH Up Token BID:$0.18 ASK:$0.19 Down Token BID:$0.81 ASK:$0.82 remaining time:11m 26s market_timestamp:1775080800
BTC Up Token BID:$0.23 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 26s market_timestamp:1775080800

ETH Up Token BID:$0.18 ASK:$0.19 Down Token BID:$0.81 ASK:$0.82 remaining time:11m 25s market_timestamp:1775080800
BTC Up Token BID:$0.23 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 25s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:11m 24s market_timestamp:1775080800
BTC Up Token BID:$0.23 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 24s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.21 Down Token BID:$0.79 ASK:$0.81 remaining time:11m 23s market_timestamp:1775080800
BTC Up Token BID:$0.23 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 23s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.21 Down Token BID:$0.79 ASK:$0.81 remaining time:11m 22s market_timestamp:1775080800
BTC Up Token BID:$0.23 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 22s market_timestamp:1775080800

ETH Up Token BID:$0.15 ASK:$0.16 Down Token BID:$0.84 ASK:$0.85 remaining time:11m 21s market_timestamp:1775080800
BTC Up Token BID:$0.20 ASK:$0.21 Down Token BID:$0.79 ASK:$0.80 remaining time:11m 21s market_timestamp:1775080800

ETH Up Token BID:$0.15 ASK:$0.17 Down Token BID:$0.83 ASK:$0.85 remaining time:11m 20s market_timestamp:1775080800
BTC Up Token BID:$0.20 ASK:$0.21 Down Token BID:$0.79 ASK:$0.80 remaining time:11m 20s market_timestamp:1775080800

ETH Up Token BID:$0.16 ASK:$0.17 Down Token BID:$0.83 ASK:$0.84 remaining time:11m 19s market_timestamp:1775080800
BTC Up Token BID:$0.20 ASK:$0.21 Down Token BID:$0.79 ASK:$0.80 remaining time:11m 19s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:11m 18s market_timestamp:1775080800
BTC Up Token BID:$0.23 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 18s market_timestamp:1775080800

ETH Up Token BID:$0.17 ASK:$0.18 Down Token BID:$0.82 ASK:$0.83 remaining time:11m 17s market_timestamp:1775080800
BTC Up Token BID:$0.22 ASK:$0.23 Down Token BID:$0.77 ASK:$0.78 remaining time:11m 17s market_timestamp:1775080800

ETH Up Token BID:$0.17 ASK:$0.18 Down Token BID:$0.82 ASK:$0.83 remaining time:11m 16s market_timestamp:1775080800
BTC Up Token BID:$0.22 ASK:$0.23 Down Token BID:$0.77 ASK:$0.78 remaining time:11m 16s market_timestamp:1775080800

ETH Up Token BID:$0.18 ASK:$0.19 Down Token BID:$0.81 ASK:$0.82 remaining time:11m 15s market_timestamp:1775080800
BTC Up Token BID:$0.22 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 15s market_timestamp:1775080800

ETH Up Token BID:$0.20 ASK:$0.21 Down Token BID:$0.79 ASK:$0.80 remaining time:11m 14s market_timestamp:1775080800
BTC Up Token BID:$0.25 ASK:$0.26 Down Token BID:$0.74 ASK:$0.75 remaining time:11m 14s market_timestamp:1775080800

ETH Up Token BID:$0.20 ASK:$0.21 Down Token BID:$0.79 ASK:$0.80 remaining time:11m 13s market_timestamp:1775080800
BTC Up Token BID:$0.25 ASK:$0.26 Down Token BID:$0.74 ASK:$0.75 remaining time:11m 13s market_timestamp:1775080800

ETH Up Token BID:$0.20 ASK:$0.21 Down Token BID:$0.79 ASK:$0.80 remaining time:11m 11s market_timestamp:1775080800
BTC Up Token BID:$0.25 ASK:$0.26 Down Token BID:$0.74 ASK:$0.75 remaining time:11m 11s market_timestamp:1775080800

ETH Up Token BID:$0.20 ASK:$0.21 Down Token BID:$0.79 ASK:$0.80 remaining time:11m 10s market_timestamp:1775080800
BTC Up Token BID:$0.25 ASK:$0.26 Down Token BID:$0.74 ASK:$0.75 remaining time:11m 10s market_timestamp:1775080800

ETH Up Token BID:$0.23 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 9s market_timestamp:1775080800
BTC Up Token BID:$0.26 ASK:$0.27 Down Token BID:$0.73 ASK:$0.74 remaining time:11m 9s market_timestamp:1775080800

ETH Up Token BID:$0.18 ASK:$0.19 Down Token BID:$0.81 ASK:$0.82 remaining time:11m 8s market_timestamp:1775080800
BTC Up Token BID:$0.25 ASK:$0.26 Down Token BID:$0.74 ASK:$0.75 remaining time:11m 8s market_timestamp:1775080800

ETH Up Token BID:$0.18 ASK:$0.19 Down Token BID:$0.81 ASK:$0.82 remaining time:11m 7s market_timestamp:1775080800
BTC Up Token BID:$0.25 ASK:$0.26 Down Token BID:$0.74 ASK:$0.75 remaining time:11m 7s market_timestamp:1775080800

ETH Up Token BID:$0.16 ASK:$0.17 Down Token BID:$0.83 ASK:$0.84 remaining time:11m 6s market_timestamp:1775080800
BTC Up Token BID:$0.23 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 6s market_timestamp:1775080800

ETH Up Token BID:$0.16 ASK:$0.17 Down Token BID:$0.83 ASK:$0.84 remaining time:11m 5s market_timestamp:1775080800
BTC Up Token BID:$0.23 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 5s market_timestamp:1775080800

ETH Up Token BID:$0.16 ASK:$0.17 Down Token BID:$0.83 ASK:$0.84 remaining time:11m 4s market_timestamp:1775080800
BTC Up Token BID:$0.23 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 4s market_timestamp:1775080800

ETH Up Token BID:$0.16 ASK:$0.17 Down Token BID:$0.83 ASK:$0.84 remaining time:11m 3s market_timestamp:1775080800
BTC Up Token BID:$0.23 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 3s market_timestamp:1775080800

ETH Up Token BID:$0.16 ASK:$0.17 Down Token BID:$0.83 ASK:$0.84 remaining time:11m 2s market_timestamp:1775080800
BTC Up Token BID:$0.23 ASK:$0.24 Down Token BID:$0.76 ASK:$0.77 remaining time:11m 2s market_timestamp:1775080800

ETH Up Token BID:$0.17 ASK:$0.18 Down Token BID:$0.82 ASK:$0.83 remaining time:11m 1s market_timestamp:1775080800
BTC Up Token BID:$0.24 ASK:$0.25 Down Token BID:$0.75 ASK:$0.76 remaining time:11m 1s market_timestamp:1775080800

ETH Up Token BID:$0.15 ASK:$0.17 Down Token BID:$0.83 ASK:$0.85 remaining time:11m 0s market_timestamp:1775080800
BTC Up Token BID:$0.22 ASK:$0.23 Down Token BID:$0.77 ASK:$0.78 remaining time:11m 0s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:10m 59s market_timestamp:1775080800
BTC Up Token BID:$0.24 ASK:$0.25 Down Token BID:$0.75 ASK:$0.76 remaining time:10m 59s market_timestamp:1775080800

ETH Up Token BID:$0.21 ASK:$0.22 Down Token BID:$0.78 ASK:$0.79 remaining time:10m 58s market_timestamp:1775080800
BTC Up Token BID:$0.27 ASK:$0.28 Down Token BID:$0.72 ASK:$0.73 remaining time:10m 58s market_timestamp:1775080800

ETH Up Token BID:$0.21 ASK:$0.22 Down Token BID:$0.78 ASK:$0.79 remaining time:10m 57s market_timestamp:1775080800
BTC Up Token BID:$0.28 ASK:$0.29 Down Token BID:$0.71 ASK:$0.72 remaining time:10m 57s market_timestamp:1775080800

ETH Up Token BID:$0.21 ASK:$0.22 Down Token BID:$0.78 ASK:$0.79 remaining time:10m 56s market_timestamp:1775080800
BTC Up Token BID:$0.27 ASK:$0.28 Down Token BID:$0.72 ASK:$0.73 remaining time:10m 56s market_timestamp:1775080800

ETH Up Token BID:$0.21 ASK:$0.22 Down Token BID:$0.78 ASK:$0.79 remaining time:10m 55s market_timestamp:1775080800
BTC Up Token BID:$0.27 ASK:$0.28 Down Token BID:$0.72 ASK:$0.73 remaining time:10m 55s market_timestamp:1775080800

ETH Up Token BID:$0.21 ASK:$0.22 Down Token BID:$0.78 ASK:$0.79 remaining time:10m 54s market_timestamp:1775080800
BTC Up Token BID:$0.28 ASK:$0.29 Down Token BID:$0.71 ASK:$0.72 remaining time:10m 54s market_timestamp:1775080800

ETH Up Token BID:$0.21 ASK:$0.22 Down Token BID:$0.78 ASK:$0.79 remaining time:10m 53s market_timestamp:1775080800
BTC Up Token BID:$0.29 ASK:$0.30 Down Token BID:$0.70 ASK:$0.71 remaining time:10m 53s market_timestamp:1775080800

ETH Up Token BID:$0.22 ASK:$0.23 Down Token BID:$0.77 ASK:$0.78 remaining time:10m 52s market_timestamp:1775080800
BTC Up Token BID:$0.31 ASK:$0.32 Down Token BID:$0.68 ASK:$0.69 remaining time:10m 52s market_timestamp:1775080800

ETH Up Token BID:$0.25 ASK:$0.26 Down Token BID:$0.74 ASK:$0.75 remaining time:10m 51s market_timestamp:1775080800
BTC Up Token BID:$0.32 ASK:$0.33 Down Token BID:$0.67 ASK:$0.68 remaining time:10m 51s market_timestamp:1775080800

ETH Up Token BID:$0.25 ASK:$0.26 Down Token BID:$0.74 ASK:$0.75 remaining time:10m 50s market_timestamp:1775080800
BTC Up Token BID:$0.29 ASK:$0.30 Down Token BID:$0.70 ASK:$0.71 remaining time:10m 50s market_timestamp:1775080800

ETH Up Token BID:$0.26 ASK:$0.27 Down Token BID:$0.73 ASK:$0.74 remaining time:10m 49s market_timestamp:1775080800
BTC Up Token BID:$0.32 ASK:$0.33 Down Token BID:$0.67 ASK:$0.68 remaining time:10m 49s market_timestamp:1775080800

ETH Up Token BID:$0.29 ASK:$0.30 Down Token BID:$0.70 ASK:$0.71 remaining time:10m 48s market_timestamp:1775080800
BTC Up Token BID:$0.34 ASK:$0.35 Down Token BID:$0.65 ASK:$0.66 remaining time:10m 48s market_timestamp:1775080800

ETH Up Token BID:$0.28 ASK:$0.29 Down Token BID:$0.71 ASK:$0.72 remaining time:10m 47s market_timestamp:1775080800
BTC Up Token BID:$0.32 ASK:$0.33 Down Token BID:$0.67 ASK:$0.69 remaining time:10m 47s market_timestamp:1775080800

ETH Up Token BID:$0.27 ASK:$0.28 Down Token BID:$0.72 ASK:$0.73 remaining time:10m 46s market_timestamp:1775080800
BTC Up Token BID:$0.30 ASK:$0.31 Down Token BID:$0.69 ASK:$0.70 remaining time:10m 46s market_timestamp:1775080800

ETH Up Token BID:$0.24 ASK:$0.25 Down Token BID:$0.73 ASK:$0.76 remaining time:10m 45s market_timestamp:1775080800
BTC Up Token BID:$0.28 ASK:$0.30 Down Token BID:$0.70 ASK:$0.72 remaining time:10m 45s market_timestamp:1775080800

ETH Up Token BID:$0.22 ASK:$0.23 Down Token BID:$0.77 ASK:$0.78 remaining time:10m 43s market_timestamp:1775080800
BTC Up Token BID:$0.25 ASK:$0.26 Down Token BID:$0.74 ASK:$0.75 remaining time:10m 43s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:10m 42s market_timestamp:1775080800
BTC Up Token BID:$0.22 ASK:$0.23 Down Token BID:$0.77 ASK:$0.78 remaining time:10m 42s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:10m 41s market_timestamp:1775080800
BTC Up Token BID:$0.21 ASK:$0.22 Down Token BID:$0.78 ASK:$0.79 remaining time:10m 41s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:10m 40s market_timestamp:1775080800
BTC Up Token BID:$0.21 ASK:$0.22 Down Token BID:$0.78 ASK:$0.79 remaining time:10m 40s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:10m 39s market_timestamp:1775080800
BTC Up Token BID:$0.21 ASK:$0.22 Down Token BID:$0.78 ASK:$0.79 remaining time:10m 39s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:10m 38s market_timestamp:1775080800
BTC Up Token BID:$0.21 ASK:$0.22 Down Token BID:$0.78 ASK:$0.79 remaining time:10m 38s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:10m 37s market_timestamp:1775080800
BTC Up Token BID:$0.22 ASK:$0.23 Down Token BID:$0.77 ASK:$0.78 remaining time:10m 37s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:10m 36s market_timestamp:1775080800
BTC Up Token BID:$0.22 ASK:$0.23 Down Token BID:$0.77 ASK:$0.78 remaining time:10m 36s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:10m 35s market_timestamp:1775080800
BTC Up Token BID:$0.22 ASK:$0.23 Down Token BID:$0.77 ASK:$0.78 remaining time:10m 35s market_timestamp:1775080800

ETH Up Token BID:$0.19 ASK:$0.20 Down Token BID:$0.80 ASK:$0.81 remaining time:10m 34s market_timestamp:1775080800
BTC Up Token BID:$0.22 ASK:$0.23 Down Token BID:$0.77 ASK:$0.78 remaining time:10m 34s market_timestamp:1775080800

